version: '3.9'
services:
  ui:
    container_name: ui
    environment:
      - NODE_ENV=production
    build:
      context: .
      dockerfile: ./packages/ui/Dockerfile
      args:
        - BUILD_CONTEXT=ui
    ports:
      - '80:80'
  pgdb:
    image: postgres:14.1-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=tasks
    restart: always
    ports:
      - "5432:5432"
    expose:
      - "5432"
    volumes:
      - db:/var/lib/postgresql/data
  server:
    container_name: server
    environment:
      - NODE_ENV=production
    build:
      context: .
      dockerfile: ./packages/server/Dockerfile
      args:
        - BUILD_CONTEXT=server
    ports:
      - '3000:3000'
    expose:
      - "3000"
    depends_on:
      - pgdb

volumes:
  db:
    driver: local